package com.anmyst.pattest.tests;

public enum TestTypes {
	ABSTRACT_FACTORY, ADAPTER, BRIDGE, BUILDER, CHAIN_OF_RESPONSIBILITY, COMMAND, COMPOSITE, DECORATOR, ITERATOR_VISITOR, MEDIATOR, MEMENTO, OBSERVER, PROTOTYPE, PROXY, SINGLETON, STATE, STRATEGY, TEMPLATE_METHOD
}
